apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    author: pradip
    enviroment: dev
  name: dev-flask
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
    author: pradip
    enviroment: dev
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
    author: pradip
    enviroment: dev
  name: dev-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      author: pradip
      enviroment: dev
  template:
    metadata:
      labels:
        app: flask
        author: pradip
        enviroment: dev
    spec:
      containers:
      - image: pankaj2934/flask-app:0.1.17
        name: flask
        ports:
        - containerPort: 5000
