apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    author: pradip
    enviroment: qa
  name: qa-flask
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
    author: pradip
    enviroment: qa
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
    author: pradip
    enviroment: qa
  name: qa-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
      author: pradip
      enviroment: qa
  template:
    metadata:
      labels:
        app: flask
        author: pradip
        enviroment: qa
    spec:
      containers:
      - env:
        - name: PLATFORM
          value: qa
        image: pankaj2934/flask-app:0.25
        name: flask
        ports:
        - containerPort: 5000
