apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    author: pradip
  name: flask
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
    author: pradip
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
    author: pradip
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      author: pradip
  template:
    metadata:
      labels:
        app: flask
        author: pradip
    spec:
      containers:
      - env:
        - name: PLATFORM
          value: qa
        image: pankaj2934/flask-app:0.8
        name: flask
        ports:
        - containerPort: 5000
