apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: qa-
commonLabels:
  enviroment: qa

images:
- name: pankaj2934/flask-app
  newName: pankaj2934/flask-app
  newTag: "0.24"

patchesStrategicMerge:
- deploymentpatch.yaml
